### ISSUE TITLE
Is there any option to do voxels smoother?

### ISSUE THREAD

**Issue by z3nth10n** [Javier-Garzo/Marching-cubes-on-Unity-3D#1]
Hi, I suppose I can speak in Spanish but I'll keep talking in English for the community.

Is there any option to make voxels shape smoother? I think yes, but I'm a little bit newbie with voxels.

I bought FastNoise (https://assetstore.unity.com/packages/tools/particles-effects/fastnoise-70706) in the past which could help me to make me an idea about this, so when I have it available I'll come with a PR.

PD: Also I have this tutorial: https://github.com/z3nth10n/AlexStv-Unity-Voxel-Block-Tutorial so I'll be investigating, I'll like to do some kind of procedural cave system with this: https://github.com/z3nth10n/AlexStv-Unity-Voxel-Block-Tutorial

In the meanwhile, you can add me on discord: @z3nth10n#0775

Thanks for your attention!

**Comment by Javier-Garzo** [comment]
**Voxel shape**
i know three ways to build a voxel terrain (geometry->organic order):

1. Cube per voxel (Minecraft like): This is the most basic way and very popular thanks to the popularization of Minecraft. Where each voxel is a cube. In this solution you can't improve the shape, you can add more cubes per space, but always conserve the cube looks like.
2. Marching Cubes: This algorithm is between the the previous and next solutions, generate more organic terrains and conserve that geometric look and need save more data to generate the terrain that the previous solutions. You can use interpolation (allow smoother shapes) and increase/decrease the voxels per space to archive more/less organic terrain and better look shape, however you will always conserve some geometric look.
3. Dual countouring: This algorithm allow to get the smoother shapes, the trade off is we need to know even more information about the terrain than Marching Cubes algorithm. The terrain look full organic like 3D game, so you dont get that geometry results obtained in the two previous solutions.


A good geometry comparation is this image from a [unity forum post](https://forum.unity.com/threads/guide-procedural-world-from-voxels-in-c.357967/) (this is a simple comparison, you can archive best looking result with each solution):
![image](https://user-images.githubusercontent.com/58559223/99518711-41733c80-2991-11eb-84b7-657cafdcc78c.png)

So you can chose the options that you prefer for you game, but the smoother one is the Dual countouring.


**Cave system**
About the cave system in your game is a problem related with the 3D noise, i need investigate about it, because this project only use 2D perlin noise to generate the height map of the terrain. The solution for caves is use a 3D noise like a matrix or something similar how you save your terrain data for allow to generate the caves.
