### ISSUE TITLE
Sphere world generation

### ISSUE THREAD

**Issue by emre-sahinn** [Javier-Garzo/Marching-cubes-on-Unity-3D#11]
Hi, how can I make spherical world shape? What should I change in marching cube algorithm to make world spherical?

**Comment by Javier-Garzo** [comment]
For a spherical world shape you will need modify the chunk system to support 3D chunk (now only have infinite X and Z) and the noise manager to generate 3D spheres (the planets). 
Another possible solution is the modify the chunk system to generate a close 3D environment (the planet surface) and when the user leave the planet show a 3D planet generated with other system ( [Example Sebastian Lague](https://www.youtube.com/watch?v=lctXaT9pxA0))

Maybe the first one will need a lot of optimization if the planet is a big one because the mesh calculations, the second option is more efficient friendly

**Comment by emre-sahinn** [comment]
Thanks! Seems like a lot of work but i will go with the first option because it will be a multplayer game which players can dig through world :')
